name: tokens-studio-tailwind

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to repository
        uses: actions/checkout@v4.1.1
      - name: install and build
        run: npm ci --save-dev typescript
      - name: publish to registry
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          scope: '@gsuiffet'
      - name: publish
        run: npm publish --access public
        # npm publish --access public

        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
