name: CI
on:
  push:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: pnpm/action-setup@v2
        with:
          version: 8.9
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: 18.x
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
#      Readme
      # todo test
      - run: pnpm run lint && pnpm run build
