name: Publish
on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: pnpm/action-setup@v2
        with:
          version: 8.9
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: 18.x
          cache: "pnpm"
          registry-url: 'https://registry.npmjs.org/'
          scope: '@gsuiffet'
      - run: pnpm install --frozen-lockfile


#      - name: build
#        run : npm run build
#      - name: publish
#        run: pnpm publish --access public
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

#          publish: pnpm run build && npm publish --access public
#          "version-packages": "changeset version && npm run prettier"


#      - name: Create Release Pull Request or Publish
#        id: changesets
#        uses: changesets/action@v1
#        with:
#          publish: npm run release
##          version: npm run version-packages
#        env:
#          GITHUB_TOKEN: ${{ secrets.TOKEN }}
##          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}


      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          # this expects you to have a npm script called version that runs some logic and then calls `changeset version`.
          version: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
